apiVersion: v1
kind: Service
metadata:
  name: pod2-service
spec:
  selector:
    app: pod2
  ports:
    - protocol: TCP
      port: 8081  # Puerto para el segundo pod
      targetPort: 3001
  type: LoadBalancer

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: pod2-container
      image: wilbersx01/pod2b:latest
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
        - name: pod2-container
          image: wilbersx01/pod2b:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 3001
